# This file contains generic settings for various aspects of data that
# ToadsTool covers.

# List of files that contain Ring Attack ring definitions.
ring_attack_files = [
    "lakitu_valley/ring_attack_0.json",
    "lakitu_valley/ring_attack_1.json",
    "lakitu_valley/ring_attack_2.json",
    "lakitu_valley/ring_attack_3.json",
    "lakitu_valley/ring_attack_4.json",
    "lakitu_valley/ring_attack_5.json",
    "cheep_cheep_falls/ring_attack_0.json",
    "cheep_cheep_falls/ring_attack_1.json",
    "cheep_cheep_falls/ring_attack_2.json",
    "cheep_cheep_falls/ring_attack_3.json",
    "cheep_cheep_falls/ring_attack_4.json",
    "cheep_cheep_falls/ring_attack_5.json",
    "shifting_sands/ring_attack_0.json",
    "shifting_sands/ring_attack_1.json",
    "shifting_sands/ring_attack_2.json",
    "shifting_sands/ring_attack_3.json",
    "shifting_sands/ring_attack_4.json",
    "shifting_sands/ring_attack_5.json",
    "blooper_bay/ring_attack_0.json",
    "blooper_bay/ring_attack_1.json",
    "blooper_bay/ring_attack_2.json",
    "blooper_bay/ring_attack_3.json",
    "blooper_bay/ring_attack_4.json",
    "blooper_bay/ring_attack_5.json",
    "peach_castle_grounds/ring_attack_0.json",
    "peach_castle_grounds/ring_attack_1.json",
    "peach_castle_grounds/ring_attack_2.json",
    "peach_castle_grounds/ring_attack_3.json",
    "peach_castle_grounds/ring_attack_4.json",
    "peach_castle_grounds/ring_attack_5.json",
    "bowser_badlands/ring_attack_0.json",
    "bowser_badlands/ring_attack_1.json",
    "bowser_badlands/ring_attack_2.json",
    "bowser_badlands/ring_attack_3.json",
    "bowser_badlands/ring_attack_4.json",
    "bowser_badlands/ring_attack_5.json",
]